plugins {
    id("java-library")
    id("eclipse")
    id("idea")
    id("maven-publish")
    id("net.neoforged.gradle.userdev") version("7.1.20")
}

// gradle.properties
val loaderVersionRange: String by extra
val minecraftVersion: String by extra
val minecraftVersionRange: String by extra
val modAuthors: String by extra
val modDescription: String by extra
val modGroupId: String by extra
val modId: String by extra
val modJavaVersion: String by extra
val modLicense: String by extra
val modName: String by extra
val modVersion: String by extra
val neoVersion: String by extra
val neoVersionRange: String by extra

version = modVersion
group = modGroupId

repositories {
    mavenLocal()
}

val baseArchivesName = "${modId}-${minecraftVersion}-neoforge"
base {
    archivesName.set(baseArchivesName)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(modJavaVersion))
    }
}

// Default run configurations.
// These can be tweaked, removed, or duplicated as needed.
runs {
    // applies to all the run configs below
    configureEach {
        // Recommended logging data for a userdev environment
        // The markers can be added/remove as needed separated by commas.
        // "SCAN": For mods scan.
        // "REGISTRIES": For firing of registry events.
        // "REGISTRYDUMP": For getting the contents of all registries.
        systemProperty("forge.logging.markers", "REGISTRIES")

        // Recommended logging level for the console
        // You can set various levels here.
        // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
        systemProperty("forge.logging.console.level", "debug")

        modSources.add(project.name, sourceSets.main.get())
    }
}

sourceSets {
    main {
        resources {
            // Include resources generated by data generators.
            srcDir("src/generated/resources")
        }
    }
}

dependencies {
    implementation("net.neoforged:neoforge:${neoVersion}")
}

tasks.withType<ProcessResources>().configureEach {
    filesMatching(listOf("META-INF/neoforge.mods.toml")) {
        expand(mapOf(
            "neoVersion" to neoVersion,
            "neoVersionRange" to neoVersionRange,
            "loaderVersionRange" to loaderVersionRange,
            "minecraftVersion" to minecraftVersion,
            "minecraftVersionRange" to minecraftVersionRange,
            "modAuthors" to modAuthors,
            "modDescription" to modDescription,
            "modId" to modId,
            "modName" to modName,
            "modLicense" to modLicense,
            "modVersion" to modVersion,
        ))
    }
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            artifact(tasks.jar.get())
        }
    }
    repositories {
        maven {
            setUrl("file://${project.projectDir}/repo")
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    javaToolchains {
        compilerFor {
            languageVersion.set(JavaLanguageVersion.of(modJavaVersion))
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

