# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false



# Minecraft And NeoForge versions
minecraftVersion=26.1.2
minecraftVersionRange=[26.1, 26.1.1]
neoVersion=26.1.2.53-beta
neoVersionRange=[26.1.0.8-beta,)
loaderVersionRange=[4,)
modJavaVersion=25

# Neoforge Partchment
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20

## Mod Properties
modId=modnametooltip
modName=Mod Name Tooltip
modLicense=MIT
modVersion=3.0.0
modGroupId=mezz.modnametooltip
modAuthors=mezz
modDescription=Minecraft mod that shows an ItemStack's mod name on its tooltip.
