modLoader="javafml" #mandatory
loaderVersion="${neoVersion}" #mandatory
license="MIT" #mandatory
#updateJSONURL="" #optional
issueTrackerURL="https://github.com/mezz/${modId}/issues?q=is%3Aissue" #optional

[[mods]] 
modId="${modId}" 
authors="${modAuthors}" 
version="${modVersion}" 
displayName="${modName}" 
#logoFile="examplemod.png" 
displayURL="https://curseforge.com/minecraft/mc-mods/mod-name-tooltip" 
description='''${modDescription}'''


[[dependencies.${modId}]]
    modId="neoforge" #mandatory
    versionRange="${neoVersion}" #mandatory
	ordering="NONE"
	side="BOTH"

[[dependencies.${modId}]]
	modId="minecraft" #mandatory
	versionRange="${minecraftVersion}" 
    ordering="NONE"
    side="CLIENT"
